### PR TITLE
effective mass fitting improve

### PR DESCRIPTION
**Pull request by zhubonan**
Improve the robustness of effective mass fitting algorithm. 
CLI and notebook examples are added.

### CODE REVIEW

**Comment by kavanase** [comment]
This looks great, thanks for the updates @zhubonan!

**Comment by kavanase** [comment]
Is this ready to merge @zhubonan?
I guess it solves #5 so can also close that. Might be worth adding whatever docstrings/notes you wanted to add for #38 now as well before merging? 😃

**Comment by zhubonan** [comment]
Yeah, will see if I can sort out #38 here as well.

**Comment by kavanase** [comment]
Great, looks good to me! Let's go ahead and merge this so? 😃

**Pull request merged**
